FROM eclipse-temurin:17-jre-focal

WORKDIR /app

# Copy the JAR file
COPY target/*.jar app.jar

# Port exposure
EXPOSE 8080

# Set environment variables
ENV SPRING_PROFILES_ACTIVE=prod

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
