apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <%= appNameKebab %>
  namespace: <%= appNameKebab %>-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - <%= appNameKebab %>.example.com
    secretName: <%= appNameKebab %>-tls
  rules:
  - host: <%= appNameKebab %>.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: <%= appNameKebab %>
            port:
              number: <%= servicePort %>

