# Étape de construction
FROM node:18-alpine as build-stage

WORKDIR /app

# Copie des fichiers de dépendances
COPY package*.json ./
RUN npm install

# Copie du code source
COPY . .

# Construction de l'application
RUN npm run build

# Étape de production
FROM nginx:stable-alpine as production-stage

# Copie des fichiers de configuration Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copie des fichiers de build de l'étape précédente
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
