apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: <%= appNameKebab %>-monitor
  namespace: <%= appNameKebab %>-ns
  labels:
    app: <%= appNameKebab %>
    release: prometheus
spec:
  selector:
    matchLabels:
      app: <%= appNameKebab %>
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
  namespaceSelector:
    matchNames:
    - <%= appNameKebab %>-ns

