apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%= appNameKebab %>
spec:
  replicas: <%= replicas %>
  template:
    spec:
      containers:
      - name: <%= appNameKebab %>
        resources:
          requests:
            memory: "<%= replicas <= 1 ? '128Mi' : '256Mi' %>"
            cpu: "<%= replicas <= 1 ? '50m' : '100m' %>"
          limits:
            memory: "<%= replicas <= 1 ? '512Mi' : '1Gi' %>"
            cpu: "<%= replicas <= 1 ? '250m' : '500m' %>"

