apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace où déployer les ressources
namespace: <%= appNameKebab %>-ns

# Liste des ressources à inclure
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
<% if (createPVC) { %>
  - pvc.yaml
<% } %>
<% if (createConfigMap) { %>
  - configmap.yaml
<% } %>
<% if (createSecrets) { %>
  - secrets.yaml
<% } %>
<% if (createIngress) { %>
  - ingress.yaml
<% } %>
<% if (enableAutoscaling) { %>
  - hpa.yaml
<% } %>

# Labels communs à ajouter à toutes les ressources
commonLabels:
  app: <%= appNameKebab %>
  environment: base

# Préfixe pour les noms des ressources
namePrefix: ""
