apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.name }}-secrets
  labels:
    app: {{ .Values.application.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if eq .Values.database.type "mysql" }}
  # MySQL password - utiliser --set database.password=mysecretpassword lors du déploiement
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | default "changeit" | b64enc | quote }}
  {{- else if eq .Values.database.type "postgresql" }}
  # PostgreSQL password
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | default "changeit" | b64enc | quote }}
  {{- else if eq .Values.database.type "mongodb" }}
  # MongoDB credentials
  SPRING_DATA_MONGODB_USERNAME: {{ .Values.database.username | default "app_user" | b64enc | quote }}
  SPRING_DATA_MONGODB_PASSWORD: {{ .Values.database.password | default "changeit" | b64enc | quote }}
  {{- end }}
  # JWT Secret for Spring Security
  JWT_SECRET: {{ .Values.security.jwtSecret | default "secretJwtKeyForSpringBootApplicationShouldBeVeryLongAndSecure" | b64enc | quote }}

