apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name }}-config
  labels:
    app: {{ .Values.application.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # Configuration de l'application
  APPLICATION_NAME: {{ .Values.application.name | quote }}
  SERVER_PORT: {{ .Values.service.targetPort | quote }}

  # Configuration de journalisation
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "INFO"

  # Configuration actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"

  # Autres variables d'environnement personnalisées
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

