apiVersion: v1
kind: Secret
metadata:
  name: <%= appNameKebab %>-secrets
  namespace: <%= appNameKebab %>-ns
  labels:
    app: <%= appNameKebab %>
type: Opaque
data:
<% if (database === 'mysql') { %>
  # MySQL password (base64 encoded)
  # Note: dans un environnement réel, ne pas stocker les vrais mots de passe dans les templates
  # Utilisez des outils comme Vault ou Sealed Secrets
  SPRING_DATASOURCE_PASSWORD: bXlzcWxwYXNzd29yZA==  # "mysqlpassword" encodé en base64
<% } else if (database === 'postgresql') { %>
  # PostgreSQL password (base64 encoded)
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXNwYXNzd29yZA==  # "postgrespassword" encodé en base64
<% } else if (database === 'mongodb') { %>
  # MongoDB credentials (base64 encoded)
  SPRING_DATA_MONGODB_USERNAME: YXBwX3VzZXI=  # "app_user" encodé en base64
  SPRING_DATA_MONGODB_PASSWORD: bW9uZ29wYXNzd29yZA==  # "mongopassword" encodé en base64
<% } %>
  # JWT Secret (base64 encoded)
  JWT_SECRET: c3VwZXJTZWNyZXRKd3RLZXlGb3JTcHJpbmdCb290QXBwbGljYXRpb24=

